#ifndef PARAMS_H
#define PARAMS_H

#define CHAINED_CHEAP_AND_QUICK
#define MAX_NUM_NODES 21
#define MAX_NUM_SIGNATURES 11
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 512
#define PERSISTENT_COUNTER_TIME 20

#endif
