#ifndef PARAMS_H
#define PARAMS_H

#define CHAINED_CHEAP_AND_QUICK
#define MAX_NUM_NODES 49
#define MAX_NUM_SIGNATURES 33
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 256
#define PERSISTENT_COUNTER_TIME 20

#endif
