#ifndef PARAMS_H
#define PARAMS_H

#define ACHILLES
#define MAX_NUM_NODES 5
#define MAX_NUM_SIGNATURES 3
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 0
#define PERSISTENT_COUNTER_TIME 20

#endif
