#ifndef PARAMS_H
#define PARAMS_H

#define ACHILLES
#define MAX_NUM_NODES 13
#define MAX_NUM_SIGNATURES 9
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 0
#define PERSISTENT_COUNTER_TIME 20

#endif
